CREATE DATABASE mp3player;    -- CRIAÇÃO DO BANCO DE DADOS 

USE mp3player;      -- USO DO BANCO DE DADOS MP3PLAYER

CREATE TABLE musicas (   
ID INT AUTO_INCREMENT,
DJ VARCHAR(255),
Titulo VARCHAR(255),    -- CRIAÇÃO DA TABELA MUSICAS COM ID, NOME DO DJ, TÍTULO DA MÚSICA, TEMPO DE DURAÇÃO DA MÚSICA E GêNERO DA MÚSICA
Tempo TIME,
Genero VARCHAR(100),
PRIMARY KEY(ID)
);