-- PART 4

USE mp3player;        -- USO DO BANCO DE DADOS MP3PLAYER

SELECT * FROM musicas
ORDER BY Titulo;      -- ORDENANDO AS MÚSICAS POR TÍTULO EM ORDEM ALFABÉTICA 

SELECT * FROM musicas
ORDER BY Genero;      -- ORDENANDO AS MÚSICAS POR GÊNERO EM ORDEM ALFABÉTICA

SELECT * FROM musicas
ORDER BY DJ;      -- ORDENANDO AS MÚSICAS POR DJ EM ORDEM ALFABÉTICA

SELECT * FROM musicas
ORDER BY Tempo;      -- ORDENANDO AS MÚSICAS POR TEMPO CRESCENTE

SELECT * FROM musicas
ORDER BY Tempo DESC;      -- ORDENANDO AS MÚSICAS POR TEMPO DECRESCENTE
